Repository stackrox/collector, pull requests merged in 2022-10, with the labels that each got.

#857 Add an extra layer for kernels to the collector full image
  kernel-modules/container/Dockerfile
Labels: build-full-images

#862 ROX-12576 3.9.x arena segfault backport
  .circleci/config.yml
  .circleci/initjob/30-set-collector-version.sh
  collector/lib/ProtoAllocator.h
Labels: build-builder-image

#855 disable ebpf on s390x
  collector/lib/HostInfo.h
  collector/test/HostInfoTest.cpp
Labels: ok-to-test, external-contributor

#845 Add s390x support--allow socketcall and inserting kernel fix
  collector/collector.cpp
  collector/lib/CollectorConfig.h
Labels: all-integration-tests, ok-to-test, external-contributor

#865 collector: force ebpf if SecureBoot undetermined only on x86_64
  collector/lib/HostHeuristics.cpp
Labels: ok-to-test, external-contributor

#877 Jv rox 12402 support packages should have the module version for master 2
  kernel-modules/support-packages/01-collector-to-rox-version-map.py
  kernel-modules/support-packages/02-fetch-collectors-metadata.sh
  kernel-modules/support-packages/run-all.sh
Labels: test-support-packages
