Repository stackrox/collector, pull requests merged in 2023-11, with the labels that each got.

#1401 Build test container on CPaaS workflow
  .github/workflows/cpaas.yml
  integration-tests/Dockerfile
Labels: build-full-images, run-cpaas-steps, run-multiarch-builds

#1404 Use a concurrency group different from the one on main
  .github/workflows/cpaas.yml
Labels: build-full-images, skip-integration-tests, run-cpaas-steps

#1405 Add ARM64 to the platforms used for the integration test container
  ansible/ci-build-tests.yml
  ansible/group_vars/platform_fcarm.yml
Labels: run-multiarch-builds

#1409 Block Garden Linux eBPF tests
  ansible/group_vars/all.yml
Labels: all-integration-tests

#1410 Block RHEL 9.3 kernel modules
  kernel-modules/BLOCKLIST
Labels: build-legacy-probes, skip-integration-tests

#1411 Skip integration-test container build
  .github/workflows/integration-test-containers.yml
Labels: skip-integration-tests

#1413 Switches ansible dev inventory to acs-team-sandbox
  ansible/dev/group_vars/all.yml
  ansible/dev/inventory_gcp.yml
Labels: skip-integration-tests

#1389 Fix multiarch full image builds on PRs
  .github/workflows/cpaas.yml
  .github/workflows/init.yml
  .github/workflows/main.yml
Labels: build-full-images, run-cpaas-steps, run-multiarch-builds

#1416 Ensure collector-builder-tag is set when a rebuild is not needed
  .github/workflows/collector-builder.yml
Labels: skip-integration-tests

#1424 Avoid kernel modules for rhel 8.9
  kernel-modules/BLOCKLIST
Labels: build-legacy-probes, build-full-images

#1425 WIP: RHTAP Onboarding: 2nd attempt
  rhtap.Dockerfile
Labels: do-not-merge/work-in-progress

#1435 Ensures boolean type for build_multi_arch
  .github/workflows/integration-test-containers.yml
  ansible/ci-build-tests.yml
Labels: run-multiarch-builds

#1438 Include master (push) events when building multiarch test containers
  .github/workflows/integration-test-containers.yml
Labels: run-multiarch-builds
