Repository stackrox/collector, pull requests merged in 2023-07, with the labels that each got.

#1229 Block failing Fedora integration tests
  ansible/group_vars/all.yml
Labels: all-integration-tests

#1239 Add .clangd file
  .clangd
Labels: skip-integration-tests

#1246 Use non-docker actionlint commit hook
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: skip-integration-tests

#1237 Use real full images on the downstream nightly
  .github/workflows/collector-full.yml
  .github/workflows/cpaas.yml
  .github/workflows/integration-tests-vm-type.yml
  .github/workflows/integration-tests.yml
  .github/workflows/main.yml
Labels: build-full-images, run-cpaas-steps

#1254 Remove deprecated Dockerfile.ubi file
  collector/container/Dockerfile.ubi
Labels: skip-integration-tests

#1260 Makes main workflow run on PR label changes
  .github/workflows/main.yml
Labels: skip-integration-tests

#1261 Add s390x to collector-slim multiarch build
  .github/workflows/collector-slim.yml
Labels: build-builder-image, build-multiarch-image

#1265 Moves most notifications to oncall channel
  .github/workflows/cpaas.yml
  .github/workflows/gardenlinux-bumper.yml
  .github/workflows/integration-tests.yml
  .github/workflows/support-packages.yml
Labels: skip-integration-tests
