Repository stackrox/collector, pull requests merged in 2024-03, with the labels that each got.

#1590 Fixes duplicate driver artifacts when build uses multiple GHA runners
  .github/workflows/check-drivers-failures.yml
  .github/workflows/collector-full.yml
  .github/workflows/drivers.yml
  .github/workflows/main.yml
  .github/workflows/upload-drivers.yml
Labels: build-legacy-probes

#1599 Block probes <=2.9.0 for linux >=6.7
  kernel-modules/BLOCKLIST
Labels: build-legacy-probes, skip-integration-tests

#1585 Split slim builds in local gha runner and remote vm
  .github/workflows/collector-slim.yml
Labels: run-multiarch-builds

#1604 ROX-18383: remove upstream drivers from support packages
  .github/actions/support-package-metadata-json/metadata.py
  .github/workflows/support-packages.yml
  kernel-modules/support-packages/04-create-support-packages.sh
  kernel-modules/support-packages/utils.sh
Labels: test-support-packages

#1582 Use Debug for PRs
  .github/workflows/collector-slim.yml
  ansible/ci-build-collector.yml
Labels: all-integration-tests

#1561 Switch CI project stackrox-ci -> acs-san-stackroxci
  .github/actions/setup-vm-creds/action.yml
  .github/workflows/integration-tests-vm-type.yml
  ansible/Makefile
  ansible/ci/group_vars/all.yml
  ansible/ci/inventory_gcp.yml
  ansible/dev/group_vars/all.yml
  ansible/group_vars/all.yml
  ansible/group_vars/gcp.yml
  ansible/roles/create-all-vms/tasks/by-family.yml
  ansible/roles/create-all-vms/tasks/by-image.yml
  ansible/roles/create-vm/tasks/create-gcp-vm.yml
  ansible/roles/create-vm/tasks/main.yml
Labels: all-integration-tests

#1605 Fix missing debug_mode variable in native builds
  .github/workflows/collector-slim.yml
Labels: run-multiarch-builds

#1589 ROX-22866: Save core dumps to collector ci artifacts
  ansible/roles/run-test-target/tasks/test-collection-method.yml
  integration-tests/suites/common/collector_manager.go
Labels: debug, 99papercuts
