Repository stackrox/collector, pull requests merged in 2024-01, with the labels that each got.

#1480 Skip health check for CPaaS workflow
  integration-tests/suites/base.go
  integration-tests/suites/mock_sensor/expect_proc.go
Labels: run-cpaas-steps

#1448 ppc64le core-bpf testing and PR testing
  .github/actions/setup-vm-creds/action.yml
  .github/workflows/collector-builder.yml
  .github/workflows/collector-slim.yml
  .github/workflows/integration-tests-vm-type.yml
  .github/workflows/integration-tests.yml
  ansible/Makefile
  ansible/ansible.cfg
  ansible/ci-build-builder.yml
  ansible/ci-build-collector-full.yml
  ansible/ci-build-collector.yml
  ansible/ci-create-build-vms.yml
  ansible/ci/group_vars/all.yml
  ansible/ci/inventory_gcp.yml
  ansible/dev/inventory_gcp.yml
  ansible/group_vars/all.yml
  ansible/group_vars/gcp.yml
  ansible/requirements.yml
  ansible/roles/create-all-vms/tasks/by-family.yml
  ansible/roles/create-all-vms/tasks/by-image.yml
  ansible/roles/create-vm/tasks/create-ppc64le-vm.yml
  ansible/roles/create-vm/tasks/create-s390x-vm.yml
  ansible/roles/create-vm/templates/ibm-cloud-inventory.j2
  ansible/roles/destroy-vm/tasks/destroy-ppc64le-vm.yml
  ansible/roles/destroy-vm/tasks/destroy-s390x-vm.yml
  ansible/roles/destroy-vm/tasks/main.yml
  ansible/roles/provision-vm/tasks/redhat.yml
  ansible/roles/run-test-target/tasks/main.yml
  ansible/roles/run-test-target/tasks/test-collection-method.yml
  ansible/vars/ppc64le.yml
  ansible/vars/s390x.yml
  collector/CMakeLists.txt
  collector/lib/HostHeuristics.cpp
  integration-tests/Dockerfile
Labels: build-full-images, integration-tests-trace-logging, run-multiarch-builds

#1486 Fixes duplicate s390x builds on master
  .github/workflows/collector-builder.yml
  .github/workflows/collector-slim.yml
Labels: run-multiarch-builds

#1493 Reenables RHCOS 4.13 eBPF tests
  ansible/group_vars/all.yml
  kernel-modules/BLOCKLIST
Labels: all-integration-tests

#1499 Use clang-17 instead of clang-15
  builder/Dockerfile
Labels: build-builder-image, run-multiarch-builds

#1506 Only create s390x build VMs when theyre needed
  .github/workflows/collector-builder.yml
  .github/workflows/collector-slim.yml
Labels: run-multiarch-builds

#1525 Add switch event
  collector/lib/KernelDriver.h
  collector/lib/ProcessSignalFormatter.cpp
Labels: all-integration-tests, run-multiarch-builds
