Repository stackrox/collector, pull requests merged in 2024-05, with the labels that each got.

#1654 Add RHEL 9.4 block for legacy module versions
  kernel-modules/BLOCKLIST
Labels: build-legacy-probes

#1665 Bump layers used on the full image to 7
  .github/workflows/collector-full.yml
Labels: build-full-images

#1668 Fix ansible full build to ensure drivers are copied correctly
  ansible/ci-build-collector-full.yml
Labels: run-multiarch-builds

#1673 Inherit secrets for driver build failure check
  .github/workflows/cpaas.yml
Labels: run-cpaas-steps

#1656 Re-enable benchmark CI step
  .flake8
  .github/workflows/benchmarks.yml
  .github/workflows/main.yml
  ansible/benchmarks.yml
  docs/labels.md
  docs/troubleshooting.md
  integration-tests/container/QA_TAG
  integration-tests/container/berserker/Dockerfile
  integration-tests/container/berserker/Makefile
  integration-tests/container/berserker/workloads/endpoints/workload.toml
  integration-tests/container/berserker/workloads/processes/workload.toml
  integration-tests/container/socat/Dockerfile
  integration-tests/images.yml
  integration-tests/scripts/baseline/format-cpu.awk
  integration-tests/scripts/baseline/format-mem.awk
  integration-tests/scripts/baseline/format.awk
  integration-tests/scripts/baseline/main.py
  integration-tests/suites/base.go
  integration-tests/suites/benchmark.go
Labels: run-benchmark

#1677 eBPF turn-off without Power
  .github/workflows/collector.yml
  .github/workflows/cpaas.yml
  ansible/group_vars/all.yml
  ansible/roles/create-vm/tasks/main.yml
  collector/lib/HostHeuristics.cpp
  kernel-modules/build/prepare-src
Labels: run-multiarch-builds

#1683 Skip EL 8 and 9 kernel modules for 3.74
  kernel-modules/BLOCKLIST
Labels: build-legacy-probes

#1690 Build 2.9.1 drivers
  RELEASED_VERSIONS
Labels: build-legacy-probes
