Repository stackrox/collector, pull requests merged in 2024-10, with the labels that each got.

#1873 Backport on 3.19: Switch ppc64le cloud region
  ansible/vars/ppc64le.yml
Labels: run-multiarch-builds

#1874 Unarchive log files before uploading artifacts
  .github/workflows/integration-tests-vm-type.yml
Labels: run-benchmark

#1879 ROX-26516: Introspection endpoint for runtime config
  collector/lib/CollectorConfigInspector.cpp
  collector/lib/CollectorConfigInspector.h
  collector/lib/CollectorService.cpp
  docs/troubleshooting.md
Labels: build-builder-image

#1884 build: Drop clamav-scan resource requests
  .tekton/collector-build.yaml
Labels: konflux-build

#1913 build: Prevent OOM kills around Collector TAs
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release

#1916 ROX-26765: Rename pipelineruns to enable on-push rerunning
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release
