Repository stackrox/collector, pull requests merged in 2024-08, with the labels that each got.

#1771 Remove unused/broken make targets
  Makefile
  docs/how-to-start.md
  utilities/lint.sh
Labels: skip-integration-tests

#1782 Check for existence of MODULE_VERSION file
  .github/actions/support-package-metadata/create-metadata-dir.sh
  kernel-modules/support-packages/03-group-by-module-version.sh
Labels: run-cpaas-steps

#1787 build: Enable Konflux triggering in PR via label
  .tekton/collector-build.yaml
Labels: konflux-build

#1807 Update Falco bumping instructions
  docs/falco-update.md
Labels: skip-integration-tests

#1763 ROX-25477: Exercise integration tests on large nodes
  .github/workflows/integration-tests.yml
  .github/workflows/main.yml
  ansible/group_vars/all.yml
  ansible/group_vars/platform_fedora_coreos_large_node.yml
  integration-tests/integration_test.go
  integration-tests/suites/ringbuf.go
Labels: large-box-integration-tests
