Repository stackrox/collector, pull requests merged in 2024-04, with the labels that each got.

#1625 ROX-23497 Fixes version comparison for support packages
  kernel-modules/support-packages/utils.sh
Labels: test-support-packages

#1626 ROX-23499: Force EBPF when Power + OCP4.12
  collector/lib/HostHeuristics.cpp
  collector/lib/HostInfo.cpp
  collector/lib/HostInfo.h
Labels: run-multiarch-builds

#1632 Fix mixed up total/single buffer size
  collector/lib/CollectorConfig.cpp
  collector/lib/CollectorConfig.h
Labels: run-multiarch-builds

#1642 Introduce USDT trace points
  builder/Dockerfile
  collector/lib/ProcessSignalHandler.cpp
Labels: run-multiarch-builds

#1648 Use event watchers for namespace events
  .github/workflows/k8s-integration-tests.yml
  integration-tests/pkg/collector/collector_k8s.go
  integration-tests/pkg/executor/executor_k8s.go
  integration-tests/suites/k8s_namespace.go
Labels: build-full-images
