Repository stackrox/collector, pull requests merged in 2024-11, with the labels that each got.

#1929 Revert "Remove --platform from start-builder target"
  Makefile
Labels: run-multiarch-builds

#1920 ROX-26026: Make `determine-image-tag` recognize git tags
  .tekton/determine-image-tag-task.yaml
Labels: backport-for-4.6-konflux-release

#1931 ROX-26026: Backport #1920 git tags handling
  .tekton/determine-image-tag-task.yaml
Labels: build-builder-image

#1932 build: Update Konflux pipelines
  .tekton/collector-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release

#1944 Pin ansible version to <2.17 to avoid loop bug (#1837)
  ansible/requirements.txt
  ansible/requirements.yml
Labels: build-builder-image

#1956 ROX-26784: Configure tekton pipelines for release branch
  .tekton/collector-build.yaml
Labels: build-builder-image

#1969 Fixes SLES permissions errors when logging into quay.io
  ansible/group_vars/all.yml
  ansible/group_vars/platform_sles.yml
  ansible/group_vars/platform_sles_arm64.yml
  ansible/roles/provision-vm/tasks/main.yml
  ansible/roles/provision-vm/tasks/sles.yml
Labels: run-multiarch-builds
