Repository stackrox/collector, pull requests merged in 2025-05, with the labels that each got.

#2097 Update ansible tasks for ppc64le
  ansible/requirements.yml
  ansible/roles/create-vm/tasks/create-ppc64le-vm.yml
  ansible/roles/destroy-vm/tasks/destroy-ppc64le-vm.yml
Labels: all-integration-tests, run-multiarch-builds

#2109 ROX-20234: Add rpms prefetch, set build to hermetic
  .github/CODEOWNERS
  .github/renovate.json5
  .konflux/README.md
  .konflux/scripts/subscription-manager-bro.sh
  .tekton/collector-build.yaml
  .tekton/collector-component-pipeline.yaml
  collector/container/konflux.Dockerfile
  rpms.in.yaml
  rpms.lock.yaml
  rpms.rhel.repo
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#2120 ROX-29078: switch to per component service account
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#2115 ROX-28568: Add required tasks sast-shell-check and sast-unicode-check to Konflux pipelines
  .tekton/collector-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#2129 chore: Bump memory limit in TA download
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#2134 build(fix): Bump TA steps memory from 4 to 6Gi
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release

#2125 Add a release workflow
  .github/workflows/release.yml
  docs/release.md
Labels: skip-integration-tests

#2106 ROX-29116: (fix) Use ARM GH action workflow runners for ARM builds
  .github/workflows/collector-builder.yml
  .github/workflows/collector.yml
  .github/workflows/init.yml
  .github/workflows/integration-tests.yml
  .github/workflows/main.yml
  .github/workflows/unit-tests.yml
  ansible/group_vars/all.yml
Labels: run-multiarch-builds

#2076 ROX-28839 - Add RHCOS images to ARM integration tests
  .github/workflows/integration-tests.yml
  ansible/group_vars/all.yml
  ansible/group_vars/platform_rhcos_arm64.yml
Labels: run-arm64-builds

#2139 ROX-29479: Use custom repos for Konflux built product
  .github/workflows/k8s-integration-tests.yml
  .github/workflows/konflux.yml
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release, backport-for-4.7-konflux-release
