Repository stackrox/collector, pull requests merged in 2025-02, with the labels that each got.

#2034 Use newer QEMU on test containers builds
  .github/workflows/integration-test-containers.yml
Labels: run-multiarch-builds

#2038 Downgrade ibm cloudcollection to 1.51.0 to workaround failures on ppc64le
  ansible/requirements.yml
Labels: all-integration-tests, run-multiarch-builds

#2039 Add arm64 to the test matrix for the downstream tests
  .github/workflows/cpaas.yml
Labels: run-cpaas-steps

#2035 ROX-27831: set image expiration based on event type and target branch
  .tekton/collector-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release
