Repository stackrox/collector, pull requests merged in 2025-01, with the labels that each got.

#2006 chore: Kill `Java` mentions from Konflux pipelines
  .tekton/collector-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release

#2007 ROX-24530: let Konflux images expire after 13w
  .tekton/collector-build.yaml
Labels: backport-for-4.6-konflux-release

#2010 Exclude socketpair prog
  collector/CMakeLists.txt
Labels: build-builder-image, all-integration-tests

#2011 [grpc] silence a few build warnings
  builder/install/40-grpc.sh
Labels: build-builder-image, run-multiarch-builds

#2001 ROX-27384: Use the updated `determine-image-tag` task
  .konflux/scripts/fail-build-if-git-is-dirty.sh
  .tekton/collector-build.yaml
  .tekton/collector-component-pipeline.yaml
Labels: backport-for-4.6-konflux-release

#2017 Move deprecated versions to RELEASED_VERSIONS.unsupported
  RELEASED_VERSIONS
  RELEASED_VERSIONS.unsupported
Labels: run-cpaas-steps

#2018 Fix image build segfaults on QEMU
  .github/workflows/collector-builder.yml
  .github/workflows/collector.yml
Labels: run-multiarch-builds
